// packages/content/src/blog/2026-07-30-uk-gtv-ja/gtv-chart/EvidenceTable.svelte
<script lang='ts'>
	import { localisePoint, resolveChartLang, uiCopy, type ChartLang } from './copy.ts';
	import { segments } from './evidence-links.ts';
	import { rows } from './rows.ts';

	let { focused = $bindable(), lang = 'ja' }: { focused: number | null; lang?: ChartLang } =
		$props();

	const resolvedLang = $derived(resolveChartLang(lang));
	const copy = $derived(uiCopy[resolvedLang].table);

	const percent = (value: number | null) => (value == null ? '—' : `${value}%`);

	const starLabel = (value: number | null) =>
		value == null ? '—' : value === 0 ? copy.almostZero : `~${value}K`;

	function scrollHorizontally(event: KeyboardEvent) {
		const direction = event.key === 'ArrowLeft' ? -1 : event.key === 'ArrowRight' ? 1 : 0;
		const element = event.currentTarget as HTMLDivElement;
		if (direction === 0 || element.scrollWidth <= element.clientWidth) {
			return;
		}

		event.preventDefault();
		element.scrollLeft += direction * 80;
	}
</script>

<!-- svelte-ignore a11y_no_noninteractive_tabindex, a11y_no_noninteractive_element_interactions (horizontal overflow must be keyboard-scrollable) -->
<div
	aria-label={copy.regionLabel}
	class='scroll'
	onkeydown={scrollHorizontally}
	role='region'
	tabindex='0'
>
	<span aria-hidden='true' class='table-scroll-hint'>← scroll →</span>
	<table>
		<caption class='sr-only'>{copy.caption}</caption>
		<thead>
			<tr>
				<th scope='col'>{copy.date}</th>
				<th class='num' scope='col'>{copy.low}</th>
				<th class='num' scope='col'>{copy.mid}</th>
				<th class='num' scope='col'>{copy.high}</th>
				<th class='num' scope='col'>{copy.stars}</th>
				<th scope='col'>{copy.notes}</th>
			</tr>
		</thead>
		<tbody>
			{#each rows as row, index (row.date)}
				{@const localised = localisePoint(row, resolvedLang)}
				<tr
					class:focused={focused === index}
					data-testid='gtv-row'
					onfocusin={() => (focused = index)}
					onfocusout={() => (focused = null)}
					onmouseenter={() => (focused = index)}
					onmouseleave={() => (focused = null)}
				>
					<th scope='row'>
						{localised.label}{copy.headingOpen}{#if localised.milestoneHref == null}{localised.milestone}{:else}<a
								href={localised.milestoneHref}
								rel='noopener noreferrer'
								target='_blank'>{localised.milestone}</a>{/if}{copy.headingClose}
					</th>
					<td class='num'>{percent(localised.low)}</td>
					<td class='num'>{localised.mid == null ? copy.frozen : `${localised.mid}%`}</td>
					<td class='num'>{percent(localised.high)}</td>
					<td class='num'>{starLabel(localised.stars)}</td>
					<td>
						{#each segments(localised) as part (part.text)}
							{#if part.href == null}
								{part.text}
							{:else if part.href.startsWith('http')}
								<a href={part.href} rel='noopener noreferrer' target='_blank'>{part.text}</a>
							{:else}
								<a href={part.href}>{part.text}</a>
							{/if}
						{/each}
					</td>
				</tr>
			{/each}
		</tbody>
	</table>
</div>

<style>
	/* spellchecker:off */
	.scroll {
		overflow-x: auto;
		margin-top: 1.5rem;
	}

	.scroll:focus-visible {
		outline: 2px solid var(--gtv-mid);
		outline-offset: 2px;
	}

	table {
		width: 100%;
		min-width: 52rem;
		border-collapse: collapse;
		font-size: 0.8125rem;
	}

	th,
	td {
		padding: 0.5rem 0.75rem;
		text-align: left;
		vertical-align: top;
		border-bottom: 1px solid var(--gtv-edge);
		overflow-wrap: normal;
	}

	thead th {
		font-weight: 600;
		white-space: nowrap;
	}

	tbody th {
		font-weight: 400;
		white-space: nowrap;
	}

	th:last-child,
	td:last-child {
		min-width: 20rem;
	}

	.num {
		text-align: right;
		font-variant-numeric: tabular-nums;
		white-space: nowrap;
	}

	tbody tr.focused {
		opacity: 1;
		background-color: color-mix(in oklab, var(--gtv-mid) 12%, transparent);
	}
	/* spellchecker:on */
</style>

// src/content/blog/2026-07-30-uk-gtv-ja/gtv-chart/EvidenceTable.tsx
import type { ChartLang } from './copy.ts';
import { For, Show } from 'solid-js';
import { localisePoint, resolveChartLang, uiCopy } from './copy.ts';
import { segments } from './evidence-links.ts';
import { rows } from './rows.ts';

type EvidenceTableProps = {
	/** Index of the focused row, or null when nothing is focused. */
	focused: number | null;
	/** Reports focus moving to a row, or clearing with null. */
	onFocusedChange: (focused: number | null) => void;
	lang?: ChartLang;
};

/**
 * Evidence table under the chart, sharing its focus with the timeline.
 */
export default function EvidenceTable(props: EvidenceTableProps) {
	const lang = () => resolveChartLang(props.lang);
	const copy = () => uiCopy[lang()].table;

	const percent = (value: number | null) => (value == null ? '—' : `${value}%`);

	const starLabel = (value: number | null) =>
		value == null ? '—' : value === 0 ? copy().almostZero : `~${value}K`;

	function scrollHorizontally(event: KeyboardEvent & { currentTarget: HTMLDivElement }) {
		const direction = event.key === 'ArrowLeft' ? -1 : event.key === 'ArrowRight' ? 1 : 0;
		const element = event.currentTarget;
		if (direction === 0 || element.scrollWidth <= element.clientWidth) {
			return;
		}

		event.preventDefault();
		element.scrollLeft += direction * 80;
	}

	// Horizontal overflow must be keyboard-scrollable, hence the tabindex.
	return (
		<div
			aria-label={copy().regionLabel}
			class='scroll'
			onKeyDown={scrollHorizontally}
			role='region'
			tabindex='0'
		>
			<span aria-hidden='true' class='table-scroll-hint'>
				← scroll →
			</span>
			<table>
				<caption class='sr-only'>{copy().caption}</caption>
				<thead>
					<tr>
						<th scope='col'>{copy().date}</th>
						<th class='num' scope='col'>
							{copy().low}
						</th>
						<th class='num' scope='col'>
							{copy().mid}
						</th>
						<th class='num' scope='col'>
							{copy().high}
						</th>
						<th class='num' scope='col'>
							{copy().stars}
						</th>
						<th scope='col'>{copy().notes}</th>
					</tr>
				</thead>
				<tbody>
					<For each={rows}>
						{(row, index) => {
							const localised = () => localisePoint(row, lang());
							return (
								<tr
									class={{ focused: props.focused === index() }}
									data-testid='gtv-row'
									onFocusIn={() => props.onFocusedChange(index())}
									onFocusOut={() => props.onFocusedChange(null)}
									onMouseEnter={() => props.onFocusedChange(index())}
									onMouseLeave={() => props.onFocusedChange(null)}
								>
									<th scope='row'>
										{localised().label}
										{copy().headingOpen}
										<Show when={localised().milestoneHref} fallback={localised().milestone}>
											{(href) => (
												<a href={href()} rel='noopener noreferrer' target='_blank'>
													{localised().milestone}
												</a>
											)}
										</Show>
										{copy().headingClose}
									</th>
									<td class='num'>{percent(localised().low)}</td>
									<td class='num'>
										{localised().mid == null ? copy().frozen : `${localised().mid}%`}
									</td>
									<td class='num'>{percent(localised().high)}</td>
									<td class='num'>{starLabel(localised().stars)}</td>
									<td>
										<For each={segments(localised())}>
											{(part) => {
												if (part.href == null) {
													return part.text;
												}

												const external = part.href.startsWith('http');
												return (
													<a
														href={part.href}
														rel={external ? 'noopener noreferrer' : undefined}
														target={external ? '_blank' : undefined}
													>
														{part.text}
													</a>
												);
											}}
										</For>
									</td>
								</tr>
							);
						}}
					</For>
				</tbody>
			</table>
		</div>
	);
}
