// src/content/blog/2026-07-30-uk-gtv-ja/gtv-chart/GtvChart.svelte
<script lang="ts">
	import type { ChartLang } from './copy.ts';
	import { onMount } from 'svelte';
	import { localisePoint, resolveChartLang, uiCopy } from './copy.ts';
	import EvidenceTable from './EvidenceTable.svelte';
	import Legend from './Legend.svelte';
	import { describeRow, rows } from './rows.ts';
	import { createScrollReveal } from './scroll-reveal.svelte.ts';
	import Timeline from './Timeline.svelte';
	import './gtv-chart.css';

	let { lang: requestedLang }: { lang?: ChartLang } = $props();
	const lang = $derived(resolveChartLang(requestedLang));
	const copy = $derived(uiCopy[lang]);
	const scrollReveal = createScrollReveal();
	let focused = $state<number | null>(null);
	const readout = $derived(
		focused == null ? '' : describeRow(localisePoint(rows[focused], lang), lang),
	);
	let figure: HTMLElement;

	onMount(() => scrollReveal.attach(figure));
</script>

<figure class="gtv-chart" data-testid="gtv-chart" bind:this={figure}>
	<Legend {lang} />
	<p aria-atomic="true" aria-live="polite" class="readout">{readout || '\u00a0'}</p>
	<div class="wipe" class:revealed={scrollReveal.revealed}>
		<Timeline {focused} {lang} onFocusedChange={(value) => (focused = value)} />
	</div>
	<EvidenceTable {focused} {lang} onFocusedChange={(value) => (focused = value)} />
	<figcaption>{copy.figcaption}</figcaption>
</figure>

// src/content/blog/2026-07-30-uk-gtv-ja/gtv-chart/GtvChart.tsx
import type { ChartLang } from './copy.ts';
import { createSignal, onSettled } from 'solid-js';
import { localisePoint, resolveChartLang, uiCopy } from './copy.ts';
import EvidenceTable from './EvidenceTable.tsx';
import Legend from './Legend.tsx';
import { describeRow, rows } from './rows.ts';
import { createScrollReveal } from './scroll-reveal.ts';
import Timeline from './Timeline.tsx';
import './gtv-chart.css';

/**
 * The GTV pass-rate timeline: legend, live readout, chart, and evidence table,
 * all sharing one focused row.
 *
 * @param props.lang - Chart language, falling back to Japanese.
 */
export default function GtvChart(props: { lang?: ChartLang }) {
	const lang = () => resolveChartLang(props.lang);
	const copy = () => uiCopy[lang()];
	const scrollReveal = createScrollReveal();

	const [focused, setFocused] = createSignal<number | null>(null);

	const readout = () => {
		const index = focused();
		return index == null ? '' : describeRow(localisePoint(rows[index], lang()), lang());
	};

	let figure!: HTMLElement;
	onSettled(() => scrollReveal.attach(figure));

	return (
		<figure class='gtv-chart' data-testid='gtv-chart' ref={figure}>
			<Legend lang={lang()} />
			<p aria-atomic='true' aria-live='polite' class='readout'>
				{readout() || '\u00a0'}
			</p>
			<div class={{ wipe: true, revealed: scrollReveal.revealed() }}>
				<Timeline focused={focused()} lang={lang()} onFocusedChange={setFocused} />
			</div>
			<EvidenceTable focused={focused()} lang={lang()} onFocusedChange={setFocused} />
			<figcaption>{copy().figcaption}</figcaption>
		</figure>
	);
}
