// packages/content/src/blog/2026-07-30-uk-gtv-ja/gtv-chart/Timeline.tsx
import type { ChartPoint } from '@tanstack/charts';
import type { ChartProps } from '@tanstack/charts/solid';
import type { Component } from 'solid-js';
import type { ChartLang } from './copy.ts';
import { createChartAdapter } from '@tanstack/charts/adapter';
import { createSignal, Show } from 'solid-js';
import { isServer } from 'solid-js/web';
import { resolveChartLang, uiCopy } from './copy.ts';
import { buildChartDefinition } from './definition.ts';
import { isRowMark } from './focus.ts';

type TimelineProps = {
	/** Index of the focused row, or null when nothing is focused. */
	focused: number | null;
	/** Reports focus moving to a row, or clearing with null. */
	onFocusedChange: (focused: number | null) => void;
	lang?: ChartLang;
};

const ASPECT_RATIO = 2.2;

/**
 * Interactive timeline chart, sharing its focus with the evidence table.
 */
export default function Timeline(props: TimelineProps) {
	const lang = () => resolveChartLang(props.lang);
	const copy = () => uiCopy[lang()].chart;
	const definition = () => buildChartDefinition(props.focused, lang());

	// `@tanstack/charts/solid` is compiled for the DOM and throws when merely
	// imported on the server, so the server (and the client until the adapter
	// chunk arrives) paints the same SVG through the framework-agnostic
	// adapter, and the interactive chart takes over once loaded.
	const prerendered = () =>
		createChartAdapter({
			definition: definition(),
			ariaLabel: copy().ariaLabel,
			ariaDescription: copy().ariaDescription,
			aspectRatio: ASPECT_RATIO,
			idPrefix: 'gtv-timeline',
		}).prerender();

	const [chart, setChart] = createSignal<Component<ChartProps> | null>(null);
	if (!isServer) {
		void import('@tanstack/charts/solid').then((module) => setChart(() => module.Chart));
	}

	// Pointer leave only clears chart focus.
	return (
		<div onPointerLeave={() => props.onFocusedChange(null)}>
			<Show
				when={chart()}
				keyed
				fallback={
					<div
						class='ts-chart-host canvas'
						style={{ position: 'relative', width: '100%', 'aspect-ratio': String(ASPECT_RATIO) }}
					>
						<div
							class='ts-chart-surface'
							style={{ width: '100%', height: '100%' }}
							innerHTML={prerendered()}
						/>
					</div>
				}
			>
				{(Chart) => (
					<Chart
						ariaLabel={copy().ariaLabel}
						ariaDescription={copy().ariaDescription}
						aspectRatio={ASPECT_RATIO}
						class='canvas'
						definition={definition()}
						onFocusChange={(point: ChartPoint | null) => {
							// Only some marks are drawn from `rows`; the rest have their own datasets.
							props.onFocusedChange(
								point != null && isRowMark(point.markId) ? point.datumIndex : null,
							);
						}}
					/>
				)}
			</Show>
		</div>
	);
}

// src/content/blog/2026-07-30-uk-gtv-ja/gtv-chart/Timeline.svelte
<script lang="ts">
	import type { ChartHostOptions } from '@tanstack/charts';
	import type { ChartLang } from './copy.ts';
	import { createChartAdapter } from '@tanstack/charts';
	import { onMount, untrack } from 'svelte';
	import { resolveChartLang, uiCopy } from './copy.ts';
	import { buildChartDefinition } from './definition.ts';
	import { isRowMark } from './focus.ts';

	type Props = {
		/** Index of the focused row, or null when nothing is focused. */
		focused: number | null;
		/** Reports focus moving to a row, or clearing with null. */
		onFocusedChange: (focused: number | null) => void;
		lang?: ChartLang;
	};

	let { focused, onFocusedChange, lang: requestedLang }: Props = $props();
	const lang = $derived(resolveChartLang(requestedLang));
	const copy = $derived(uiCopy[lang].chart);
	const ASPECT_RATIO = 2.2;
	const options: ChartHostOptions = $derived({
		definition: buildChartDefinition(focused, lang),
		ariaLabel: copy.ariaLabel,
		ariaDescription: copy.ariaDescription,
		aspectRatio: ASPECT_RATIO,
		idPrefix: 'gtv-timeline',
		onFocusChange: (point) => {
			// Only some marks are drawn from `rows`; the rest have their own datasets.
			onFocusedChange(point != null && isRowMark(point.markId) ? point.datumIndex : null);
		},
	});
	// The adapter takes an initial snapshot; the effect below owns subsequent updates.
	const adapter = createChartAdapter(untrack(() => options));
	const prerendered = adapter.prerender();
	let surface: HTMLDivElement;

	onMount(() => {
		adapter.mount(surface);
		return () => adapter.destroy();
	});
	$effect(() => {
		const next = options;
		untrack(() => adapter.update(next));
	});
</script>

<!-- Pointer leave only clears chart focus. -->
<!-- svelte-ignore a11y_no_static_element_interactions -->
<div onpointerleave={() => onFocusedChange(null)}>
	<div
		class="ts-chart-host canvas"
		style:position="relative"
		style:width="100%"
		style:aspect-ratio={ASPECT_RATIO}
	>
		<div bind:this={surface} class="ts-chart-surface" style:width="100%" style:height="100%">
			{@html prerendered}
		</div>
	</div>
</div>
