// src/content/blog/2026-07-30-uk-gtv-ja/gtv-chart/GtvChart.tsx
import type { ChartLang } from './copy.ts';
import { createSignal, onSettled } from 'solid-js';
import { localisePoint, resolveChartLang, uiCopy } from './copy.ts';
import EvidenceTable from './EvidenceTable.tsx';
import Legend from './Legend.tsx';
import { describeRow, rows } from './rows.ts';
import { createScrollReveal } from './scroll-reveal.ts';
import Timeline from './Timeline.tsx';
import './gtv-chart.css';

/**
 * The GTV pass-rate timeline: legend, live readout, chart, and evidence table,
 * all sharing one focused row.
 *
 * @param props.lang - Chart language, falling back to Japanese.
 */
export default function GtvChart(props: { lang?: ChartLang }) {
	const lang = () => resolveChartLang(props.lang);
	const copy = () => uiCopy[lang()];
	const scrollReveal = createScrollReveal();

	const [focused, setFocused] = createSignal<number | null>(null);

	const readout = () => {
		const index = focused();
		return index == null ? '' : describeRow(localisePoint(rows[index], lang()), lang());
	};

	let figure!: HTMLElement;
	onSettled(() => scrollReveal.attach(figure));

	return (
		<figure class='gtv-chart' data-testid='gtv-chart' ref={figure}>
			<Legend lang={lang()} />
			<p aria-atomic='true' aria-live='polite' class='readout'>
				{readout() || '\u00a0'}
			</p>
			<div class={{ wipe: true, revealed: scrollReveal.revealed() }}>
				<Timeline focused={focused()} lang={lang()} onFocusedChange={setFocused} />
			</div>
			<EvidenceTable focused={focused()} lang={lang()} onFocusedChange={setFocused} />
			<figcaption>{copy().figcaption}</figcaption>
		</figure>
	);
}

// packages/content/src/blog/2026-07-30-uk-gtv-ja/gtv-chart/GtvChart.svelte
<script lang='ts'>
	import { createScrollReveal } from '../../../lib/scroll-reveal.svelte.ts';
	import { localisePoint, resolveChartLang, uiCopy, type ChartLang } from './copy.ts';
	import EvidenceTable from './EvidenceTable.svelte';
	import Legend from './Legend.svelte';
	import { describeRow, rows } from './rows.ts';
	import Timeline from './Timeline.svelte';

	let { lang = 'ja' }: { lang?: ChartLang } = $props();

	const resolvedLang = $derived(resolveChartLang(lang));
	const copy = $derived(uiCopy[resolvedLang]);
	const scrollReveal = createScrollReveal();

	let focused = $state<number | null>(null);

	const readout = $derived(
		focused == null ? '' : describeRow(localisePoint(rows[focused], resolvedLang), resolvedLang),
	);
</script>

<figure class='gtv-chart' data-testid='gtv-chart' {@attach scrollReveal.attach}>
	<Legend lang={resolvedLang} />
	<p aria-atomic='true' aria-live='polite' class='readout'>{readout || '\u00a0'}</p>
	<div class='wipe' class:revealed={scrollReveal.revealed}>
		<Timeline bind:focused lang={resolvedLang} />
	</div>
	<EvidenceTable bind:focused lang={resolvedLang} />
	<figcaption>
		{copy.figcaption}
	</figcaption>
</figure>

<style>
	/* spellchecker:off */
	.gtv-chart {
		--gtv-mid: oklch(55% 0.2 260);
		--gtv-band: oklch(55% 0.2 260);
		--gtv-edge: oklch(55% 0.02 260);
		--gtv-stars: oklch(58% 0.2 25);
		--gtv-surface: white;

		margin-block: 2rem;
	}

	:global(html.dark) .gtv-chart {
		--gtv-mid: oklch(72% 0.16 260);
		--gtv-band: oklch(72% 0.16 260);
		--gtv-edge: oklch(70% 0.02 260);
		--gtv-stars: oklch(70% 0.18 25);
		--gtv-surface: oklch(20% 0.01 260);
	}

	.readout {
		margin: 0 0 0.25rem;
		font-size: 0.8125rem;
		font-variant-numeric: tabular-nums;
		color: var(--gtv-mid);
	}

	figcaption {
		margin-top: 0.75rem;
		font-size: 0.75rem;
		line-height: 1.6;
		opacity: 0.6;
	}

	/* The chart itself never animates, so hover stays instant. */
	.wipe {
		clip-path: inset(0 100% 0 0);
		transition: clip-path 900ms ease-out;
	}

	.wipe.revealed {
		clip-path: inset(0);
	}

	@media (prefers-reduced-motion: reduce) {
		.wipe {
			clip-path: inset(0);
			transition: none;
		}
	}
	/* spellchecker:on */
</style>
